### PR TITLE
Integrates new style of checkboxes

### PR DESCRIPTION
**Pull request by baccigalupi**
The first chunk of work is getting the styling right in the styles.html
page.
        * Duplicates radio to CheckboxSelector; extracts content part
        * Build css for custom checkboxes that matches radios

The next chunk of work is about integrating that work into the ID/DL
selection page for new licenses.

### CODE REVIEW

**Comment by baccigalupi** [comment]
Looks like there is an issue with the tests. Will work on this and ping you later.

**Comment by baccigalupi** [comment]
@kyliepace This is working now. I cleaned up a bit of the duplication that made sense. There is definitely more that is out of scope to figure out. So I want to leave this as is.

**Comment by baccigalupi** [comment]
Oh wait. This was merged already. Sorry I missed that!

**Comment by kyliepace** [comment]
my bad I didn't delete the branch!

**Comment by baccigalupi** [comment]
No, you were just too on top of it!

**Pull request merged**
